[project]
channels = ["conda-forge"]
name = "mkdocs-marimo"
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64", "win-64"]

[tasks]
postinstall = "pip install --no-deps --no-build-isolation --disable-pip-version-check -e ."

[dependencies]
htmlmin = ">=0.1.13,<0.2"
marimo = ">=0.9.11"
mkdocs = ">=1.6.1,<2"
python = ">=3.9"

[host-dependencies]
hatchling = "*"
pip = "*"

[feature.test.dependencies]
mypy = "*"
pytest = "*"
[feature.test.tasks]
test = "pytest -xs"

[feature.docs.dependencies]
mkdocs = "*"
mkdocs-material = "*"
# For examples
matplotlib-base = "*"
numpy = "*"
pandas = "*"
[feature.docs.tasks]
docs = "mkdocs serve"
docs-build = "mkdocs build"

[feature.lint.dependencies]
pre-commit = "*"
pre-commit-hooks = "*"
ruff = "*"
taplo = "*"
typos = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[feature.build.dependencies]
hatchling = "*"
python-build = "*"

[feature.py39.dependencies]
python = "3.9.*"
[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[environments]
build = { features = ["build"], no-default-feature = true }
default = ["test", "py312", "docs"]
docs = ["docs"]
lint = { features = ["lint"], no-default-feature = true }
py310 = ["test", "py310"]
py311 = ["test", "py311"]
py312 = ["test", "py312"]
py39 = ["test", "py39"]
